// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cedekap.Core.Models.Entities
{
    public partial class Store
    {
        public Store()
        {
            Article = new HashSet<Article>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string PostCode { get; set; }
        public string Address { get; set; }
        public string Place { get; set; }

        public virtual ICollection<Article> Article { get; set; }
    }
}