// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diplomski.Core.Models.Entities
{
    public partial class Article
    {
        public Guid Id { get; set; }
        public string CodeDob { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal Entry { get; set; }
        public decimal Exit { get; set; }
        public decimal SingularPrice { get; set; }
        public decimal Owe { get; set; }
        public decimal Demand { get; set; }
        public decimal Tariff { get; set; }
        public string Pla { get; set; }
        public decimal Op { get; set; }
        public decimal Rebate { get; set; }
        public decimal BuyPrice { get; set; }
        public decimal Tax { get; set; }
        public Guid StoreId { get; set; }

        public virtual Store Store { get; set; }
    }
}