// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diplomski.Core.Models.Entities
{
    public partial class Article
    {
        public Guid Id { get; set; }
        public string CodeSupplier { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal Exit { get; set; }
        public decimal Price { get; set; }
        public decimal Demand { get; set; }
        public double Tariff { get; set; }
        public string Pay { get; set; }
        public int Operator { get; set; }
        public decimal Rebate { get; set; }
        public decimal BuyPrice { get; set; }
        public DateTime Month { get; set; }
        public Guid StoreId { get; set; }

        public virtual Store Store { get; set; }
    }
}