// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Diplomski.Core.Models.Entities
{
    public partial class Store
    {
        public Guid Id { get; set; }

        public virtual Article Article { get; set; }
    }
}